#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
cd $OPENSHIFT_DATA_DIR
if [ -d play-2.2.1 ]; then
    echo "Play framework already installed"
else
    wget http://downloads.typesafe.com/play/2.2.1/play-2.2.1.zip
    unzip play-2.2.1.zip
    rm -f play-2.2.1.zip
    sed -i'' -e 's/Xms512M/Xms400M/' play/framework/build
    sed -i'' -e 's/Xmx1536M/Xmx400M/' play/framework/build
    PATH=$OPENSHIFT_DATA_DIR/play-2.2.1:$PATH
    echo $PATH > ~/.env/user_vars/PATH
fi

cd $OPENSHIFT_REPO_DIR/app
play stage
nohup $OPENSHIFT_REPO_DIR/app/target/universal/stage/bin/app -Dhttp.address=$OPENSHIFT_DIY_IP -Dhttp.port=$OPENSHIFT_DIY_PORT -mem 400 > server.log 2>&1 &
