#!/bin/bash
# This is free and unencumbered software released into the public domain.

# Anyone is free to copy, modify, publish, use, compile, sell, or
# distribute this software, either in source code form or as a compiled
# binary, for any purpose, commercial or non-commercial, and by any
# means.

# In jurisdictions that recognize copyright laws, the author or authors
# of this software dedicate any and all copyright interest in the
# software to the public domain. We make this dedication for the benefit
# of the public at large and to the detriment of our heirs and
# successors. We intend this dedication to be an overt act of
# relinquishment in perpetuity of all present and future rights to this
# software under copyright law.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.

cd $OPENSHIFT_DATA_DIR
if [ -d play-2.2.1 ]; then
    echo "Play framework already installed"
else
    wget http://downloads.typesafe.com/play/2.2.1/play-2.2.1.zip
    unzip play-2.2.1.zip
    rm -f play-2.2.1.zip
    sed -i'' -e 's/Xms512M/Xms400M/' play/framework/build
    sed -i'' -e 's/Xmx1536M/Xmx400M/' play/framework/build
    PATH=$OPENSHIFT_DATA_DIR/play-2.2.1:$PATH
    echo $PATH > ~/.env/user_vars/PATH
fi

cd $OPENSHIFT_REPO_DIR/app
play stage
nohup $OPENSHIFT_REPO_DIR/app/target/universal/stage/bin/app -Dhttp.address=$OPENSHIFT_DIY_IP -Dhttp.port=$OPENSHIFT_DIY_PORT -mem 400 > server.log 2>&1 &
